# Generated by Django 4.1.5 on 2023-01-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='name1',
        ),
    ]
