# Generated by Django 4.1.5 on 2023-01-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_rename_name_role_name1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name1',
            new_name='name',
        ),
    ]
